config/routes.rb
Rails.application.routes.draw do

   root 'welcome#root'

  shallow do
   resources :users, only: [:index, :new, :create] do
    resources :social_handles, only: [:index, :create, :new]
    end
  end

  resources :admins, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]

  get '/car_free_nyc' => 'welcome#root'
  get '/pledge' => 'users#new'
  post '/created_pledge' => 'users#create'
  get '/pledge_confirmation' => 'users#index'
  get '/sponsors' => 'welcome#sponsors'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/data' => 'admins#index'
  post '/admins/create' => 'admins#create'

end

app/models/admin.rb
class Admin <ActiveRecord::Base
	has_secure_password
end

app/models/social_handle.rb
class SocialHandle < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_xlsx
	has_many :social_handles
end

app/controllers/admins_controller.rb
class AdminsController <ApplicationController
	before_action :authorize
	before_action :counter

	def new
		@admin=Admin.new
	end

	def create
		@admin = Admin.create(username: params[:admin][:username], password: params[:admin][:password], password_confirmation: params[:admin][:password_confirmation])
		@admin.save
		redirect_to login_url
	end

	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url unless current_user
  end

  def counter
    @counter = User.all.length
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
	before_action :counter 

	def new
		if session[:admin_id]
			redirect_to admins_url
		end
	end

	#/
	def create
		admin = Admin.find_by(username: params["/login"][:username])
		if admin && admin.authenticate(params["/login"][:password])
			session[:admin_id] = admin.id
			flash[:notice] = "Welcome #{admin.username}"
			redirect_to admins_url
		else
			flash[:notice] = "Incorrect e-mail and/or password. Please try again."
			render :new
		end
	end

	#/logout
	def destroy
		session[:admin_id] = nil
		flash[:notice] = "You are logged out"
		redirect_to login_url
	end
end

app/controllers/social_handles_controller.rb
class SocialHandlesController < ApplicationController
	# before_action :counter
	# def index
	# end

	# def new
	# 	@socialHandle = SocialHandle.new
	# end

	# def create
	# end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :counter

	def index
		@users = User.all.order("date desc")
	end

	def new
		@user=User.new
	end

	def create
		@user = User.create user_params
		@user.date = DateTime.now
		@user.save
		if @user.save
			@user.social_handles.create social_params
			flash[:notice] = "Thank you " + @user.f_name + " for your pledge!"
			redirect_to pledge_confirmation_url
		end
	end

end

private
	def user_params
		params.require(:user).permit(:f_name, :l_name, :e_mail, :commitment, :org, :date, :share_info, :make_public)
	end

	def social_params
		params.require(:social_handle).permit(:twitter, :facebook, :instagram)
	end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController
	before_action :counter
	
	def root
		@users = User.all
	end

	def sponsors
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/admins/index.html.erb
<%= stylesheet_link_tag "application" %>
<div class="container">
  <body>
    <div class="row">
      <h1 class="title">Export Data to Excel</h1>
    </div>
    <div class="row">
      <%= link_to "logout", logout_url %> |
      <%= link_to "Create a New Admin", new_admin_path %> |
      <%= link_to "Download as Excel", users_url(format: "xlsx") %>
    </div>
  </body>
</div>

app/views/admins/new.html.erb
<%= stylesheet_link_tag "application" %>
<div class="container">
  <body>
    <div class="row">
      <h1 class="title">Add a User to the Admin</h1>
    </div>
    <div class="row">
      <%= form_for @admin, url: {action: "create"} do |f| %>
      <%=f.label :username %>
      <%=f.text_field :username %>
    </div>
    <div class="row">
      <%=f.label :password %>
      <%=f.password_field :password %>
    </div>
    <div class="row">
      <%=f.label :password_confirmation %>
      <%=f.password_field :password_confirmation %>
    </div>
    <div class="row">
      <%=f.submit "Create User" %>
      <% end %>
    </div>
  </body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>CarFreeNyc</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="../app.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="js/bootstrap.min.js"></script> -->
    <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
  </head>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "header" %>
  <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">

        <ul class="nav navbar-nav">
          <li><img class="img-responsive everypagelogo" src="assets/CFD Logo.jpg"></li>
          <li><a href="/car_free_nyc">About Us</a></li>
          <li><a href="/pledge">Make a Pledge!</a></li>
          <li><a href="/pledge_confirmation">Pledges So Far: <b><i><%= @counter%></b></i></a></li>
          <li><a href="/sponsors">Sponsors</a></li>
        </ul>
    </nav>
    <body>
    <%=notice%>
    <%=yield%>
    </body>
  </div>
  <footer>
    <div class="footerorg">
      <img src="assets/GA Logo.jpg" class="footerlogo">
      <img src="assets/CFD Logo.jpg" class="footerlogo">
    Website co-hosted by General Assemby and Car Free NYC
    </div>
    <a href="/login" class="admin">Admin</a>
  </footer>
</html>

app/views/users/index.html.erb
<%= stylesheet_link_tag "application" %>
<img src="assets/CFD Logo.jpg" class="img-responsive logo">
<div class="container">
	<div class="pledgebox">
		<div class="row">
			<h1 class="title">Earth Day Pledges</h1>
		</div>
		<div class="row">
			<ul class="listpledge">
				<%@users.each do |user|%>
				<div class="row">
					<%if user.make_public === true%>
						<li><h4><%=user.f_name%> from <%=user.org%> pledges to <%=user.commitment%></h4></li>
					<%end%>
				</div>
				<%end%>
			</ul>
		</div>
	</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "new_user" %>
<div class="form-holder">
	<h1 class"title">Make a Pledge!</h1>
	<div class="row">
		<div class="col-md-4"></div>
  	<div class="form-group">
  		<div class="col-md-4">
				<%=form_for @user do |f|%>
					<%=f.label(:f_name, "First Name", class: 'required') %>
					<%=f.text_field :f_name, class: 'form-control', :required => true %>
			 </div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
					<%=f.label(:l_name, "Last Name", class: 'required')%>
					<%=f.text_field :l_name, class: 'form-control', :required => true %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
					<%=f.label(:e_mail,"E-mail", class: 'required')%>
					<%=f.text_field :e_mail, class: 'form-control', :required => true %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
					<%=f.label(:commitment, "I pledge to", class: 'required')%>
					<%=f.text_area :commitment, class: 'form-control', rows: '5', :required => true %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
					<%=f.label(:org, "Organization", class: 'required')%>
					<%=f.text_field :org, class: 'form-control', :required => true %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
				<%=fields_for :social_handle do |social_handle_field|%>
					<%=social_handle_field.label(:twitter, "Twitter Handle")%>
					<%=social_handle_field.text_field :twitter, class: 'form-control' %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
				<%=social_handle_field.label(:facebook, "Facebook Page")%>
				<%=social_handle_field.text_field :facebook, class: 'form-control' %>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="col-md-4"></div>
		<div class="form-group">
			<div class="col-md-4">
				<%=social_handle_field.label(:instagram, "Instagram")%>
				<%=social_handle_field.text_field :instagram, class: 'form-control' %>
				<%end%>
			</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="form-group">
			<div class="col-md-4"></div>
			<div class="col-md-8">
				<%= f.check_box :share_info, options = {:checked => true} %>
				<%= f.label :share_info, "Share my contact information with partners Earth Day Initiative and General Assembly to stay up to date about their programs and events.", class: 'space' %>
			</div><!--ends dive col-md-8-->
		</div><!--ends div form-group-->
	</div><!--end div row-->
	<div class="row">
		<div class="form-group">
				<div class="col-md-4"></div>
					<div class="col-md-8">
						<%= f.check_box :make_public, options = {:checked => true} %>
						<%= f.label :make_public, "Make my name, organization, and pledge public!", class:'space' %>
				</div><!--ends dive col-md-8-->
			</div><!--ends div form-group-->
		</div><!--end div row-->
	<div class="row">
		<div class="form-group">
			<div class="col-md-4"></div>
				<div class="col-md-4">
						<%=f.submit "Submit", class: "btn btn-default" %>
				</div><!--ends dive col-md-4-->
		</div><!--ends div form-group-->
		<%end%>
	</div>
</div><!--ends div form-holder-->

app/views/welcome/root.html.erb
<%= stylesheet_link_tag "application" %>
<div class="container">
  <body>
    <div class="row">
      <h1 class="title"> Welcome to Car Free NYC 2016</h1>
      <div class="pledgenpic">
      <div class"pledgebtn">
        <a href="/pledge" class="btn btn-danger btn-lg active" role="button">Pledge Now!</a>
      </div>
        <img class="img-responsive car_less" src="assets/car-less.jpg">
      </div>
      <h2 class="about">About Us</h2>
    </div>
    <div class="row">
	   <p>The mission of Car Free Day NYC is to encourage New York City drivers to choose alternative means of moving about NYC on Earth Day, April 22nd, 2016.</p>
	    <p>Car Free Day NYC is an idea that we hope will spark a movement. It addresses critical issues facing our city, our country and our world that stem in part from having too many cars on our city’s streets. From sustainability and environmental justice to land use and urban planning as well as public health and street safety, our overuse of cars has caused numerous urban problems that have mounting social and economic costs.</p>
	     <p>Car Free Day NYC is about encouraging people to make more thoughtful decisions in their daily lives, particularly related to transportation. We are proposing to have Earth Day be a day where we drastically limit the number of cars on New York City streets, by encouraging residents and commuters to choose one of the many other forms of transportation that New York offers for one day of the year.</p>
    </div>
    <div class="row">
    <h2>Why</h2>
		  <ul>
  			<li>Promote investments &amp; prioritize alternative forms of transportation &lpar;public transit, cycling, walking, etc.&rpar;</li>
  			<li>Highlight the inefficiency of single passenger car usage.</li>
  			<li>Highlight the benefits of a city with fewer cars&colon;</li>
    		<ul>
  				<li><strong>Environmental Benefits:</strong> measurably reduce emissions in NYC.</li>
  				<li><strong>Cost Benefits:</strong> Dangerous emissions lead to greater health issues, long term costs of global warming.</li>
  				<li><strong>Safety Benefits:</strong> fewer cars mean safer streets for other street users.</li>
  				<li><strong>Stress Levels:</strong> Cars cause congestion and noise &ndash; studies show that noise reduction lowers stress levels.</li>
  				<li><strong>Alternate use of streets:</strong> Highlight and promote the creativity born out of minimizing the street space used by cars &lpar;plazas, cafes, restaurants, etc.&rpar; as well as the amazing existing transportation system in NYC. </li>
			  </ul>
		  </ul>
    </div>
    <div class="row">
	  <h2>2016 Goals</h2>
		  <ol>
  			<li>Considerably reduce fleets of non-essential vehicles, both public and private.</li>
  			<li>Obtain and leverage partnerships to offer incentives to commuters for getting around the city in alternative ways, as well as asking companies &amp; organizations to limit their own car use on Earth Day.</li>
  			<li>New Yorkers will be asked to leave their cars at home through an array of marketing including through social media and peer&dash;to&dash;peer contact.</li>
  			<li>Programming done by local Community Based Organizations in partnership with NYC DOT via select street closings will focus on environmentalism and the impacts of climate change on NYC and the world and what we can do as a city to address them.</li>
  			<li>Highlight the many ways the city is looking to limit its carbon footprint, both through transportation and otherwise.</li>
		  </ol>
    </div>
    <div class="row">
  	<h2>How your organization can get involved!</h2>
  		<ul>
  			<li>Pledge to go car free, either individually or through a reduction in your organization’s fleet.</li>
  			<li>Incentivize carpooling or enable employees to telecommute on Earth Day.</li>
  			<li>Help spread the message through e&dash;blasts to your constituency or organization partners&semi; social media, etc.</li>
  			<li>Offer programming or educational activities on Earth Day related to sustainability or alternatives in transportation.</li>
  		</ul>
    </div>
  </body>
</div>

app/views/welcome/sponsors.html.erb
<%= stylesheet_link_tag "application" %>
<div class="container">
  <!-- <h1 class="title"></h1> -->
    <img class="img-responsive sponsor" src="/assets/Car Free Flier.jpg" alt="flier">
</div>